apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reversewords-claim
  namespace: reverse-words-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
